### PR TITLE
optimize: replace if..else by match

### PR DESCRIPTION
**Pull request by harlanc**

### CODE REVIEW

**Review by metaclips — APPROVED** [review]

**Comment by metaclips** [comment]
Thanks @harlanc

**Comment by rainliu** [comment]
what's the difference between this one and https://github.com/webrtc-rs/rtp/pull/10?

**Comment by harlanc** [comment]
@rainliu the contents are the same but I use different users to commit, @metaclips  know the reasons.

**Comment by metaclips** [comment]
@harlanc I don't think its possible to delete PR records. We could delete the commit from the PR though.

**Pull request merged**
