### PR TITLE
optimize codes : replace if else  by match

### PR DESCRIPTION
**Pull request by harlanc**
optimize

### CODE REVIEW

**Review by metaclips — APPROVED** [review]

**Comment by metaclips** [comment]
Thanks @harlanc

**Comment by rainliu** [comment]
@metaclips , where is this commit merged into? I didn't find the merged commit in main branch.

cc @harlanc

**Comment by harlanc** [comment]
@rainliu  Can this pull request record be deleted?

**Comment by harlanc** [comment]
@rainliu @metaclips  can this pull request record be deleted?

**Comment by metaclips** [comment]
@harlanc  You can edit your commits and `git push -f` https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by harlanc** [comment]
@metaclips thanks, the commit is already cleared.

**Pull request merged**
